version: 2
jobs:
  build-ldist:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install lambda-setuptools
      - run: python setup.py ldist
      - run: ls -al dist/
  build-lupload:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py lupload --access-key=${ACCESS_KEY_ID} --secret-access-key=${SECRET_ACCESS_KEY} --s3-bucket=${S3_BUCKET} --s3-prefix=quinovas/appsync-athena-resolver/

workflows:
  version: 2
  build-only:
    jobs:
      - build-ldist:
          filters:
            branches:
              only:
                - develop
  build-and-upload:
    jobs:
      - build-lupload:
          context: lambdalambdalambda
          filters:
            branches:
              only:
                - master
